version: "3.9"

services:
  task-web:
    build: ./task-api         # <--- CLAVE: Busca el Dockerfile dentro de la carpeta
    container_name: task-web
    volumes:
      - ./task-api:/app       # <--- CLAVE: Monta solo la carpeta del código
      - /app/node_modules     # Evita borrar las librerías instaladas dentro
    ports:
      - "3200:3200"
    depends_on:
      task-db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3200
      # Conexión a BD
      POSTGRES_HOST: task-db
      POSTGRES_USER: tevis
      POSTGRES_PASSWORD: tevis123!
      POSTGRES_DB: fiis_development
      POSTGRES_PORT: 5432
      # Seguridad
      JWT_SECRET: super-secret-demo
      JWT_EXPIRES_IN: 15m
    networks:
      - tasks-net
    command: ["npm", "run", "dev"]

  task-db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: tevis
      POSTGRES_PASSWORD: tevis123!
      POSTGRES_DB: fiis_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./task-api/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tasks-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tevis -d fiis_development"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  tasks-net:
    driver: bridge